server:
  applicationConnectors:
    - type: http
      port: 2001
  adminConnectors:
    - type: http
      port: 2002

dataSource:
  driverClass: org.h2.Driver
  user: theChosenOne
  password: abc123
  url: jdbc:h2:mem:db1
  validationQuery: "/* Health check */ SELECT 1"

logging:
  level: INFO
