server:
  applicationConnectors:
    - type: http
      port: 2001
  adminConnectors:
    - type: http
      port: 2002

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:tcp://localhost/~/.gradle-bootstrap/db/server
  user: sa
  validationQuery: "/* Health check */ SELECT 1"

downloadDirectory: build/web/downloads

logging:
  level: INFO
